# Generated by Django 3.1.7 on 2021-02-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(to='ecommerce.Tag'),
        ),
    ]
