# Generated by Django 3.1.7 on 2021-02-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210224_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Delivered')], default='Pending', max_length=25),
        ),
    ]
