# Generated by Django 3.1.7 on 2021-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Shipped', 'shipped'), ('Delivered', 'delivered')], default='Pending', max_length=30),
        ),
    ]
