# Generated by Django 3.1.7 on 2021-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
